# Server Port Configuration
server.port=8082

# PostgreSQL database configuration
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/droppy}
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:1234}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# JPA / Hibernate configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# Liquibase configuration
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml

# FastAPI AI service URL
droppy.ai.url=http://localhost:8001

# Active Devices list (default MAC address from CSV)
droppy.devices=1C:69:20:35:73:C4
